name: chatx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


# Firebase
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  

# bloC
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

    # Custom Repository
  user_repository:
    path: packages/user_repository/
  post_repository:
    path: packages/post_repository/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
